name: Update GitHub Activity

on:
  workflow_dispatch:
  push:
    branches: 
        master

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "luhongxuan"
          GITHUB_TOKEN: ${{ secrets.TOKEN }}